image: alpine:latest

pages:
  stage: deploy
  script:
    - apk add --no-cache bash coreutils
    - mkdir -p public
    - cp -r $(ls -A | grep -v '^public$') public/
  artifacts:
    paths:
      - public
  only:
    - main
